### ISSUE TITLE
Failure when compiling from source on Ubuntu xenial

### ISSUE THREAD

**Issue by arocchi** [roboptim/roboptim-core#115]
I get the following errors when compiling roboptim on ubuntu xenial (16.04)

```
[  2%] Building CXX object src/CMakeFiles/roboptim-core.dir/generic-solver.cc.o
cd /home/arocchi/Code/robotology-superbuild/external/roboptim-core/build/src && /usr/bin/c++   -Droboptim_core_EXPORTS -I/home/arocchi/Code/robotology-superbuild/external/roboptim-core/build -I/home/arocchi/Code/robotology-superbuild/external/roboptim-core/build/include -I/home/arocchi/Code/robotology-superbuild/external/roboptim-core/include -isystem /usr/include/eigen3  -Werror  -pedantic -Wno-long-long -Wall -Wextra -Wcast-align -Wcast-qual -Wformat -Wwrite-strings -Wconversion -DROBOPTIM_DO_NOT_CHECK_ALLOCATION -fvisibility=hidden -DROBOPTIM_STORAGE_ORDER=ColMajor -fPIC   -I/usr/include/eigen3 -o CMakeFiles/roboptim-core.dir/generic-solver.cc.o -c /home/arocchi/Code/robotology-superbuild/external/roboptim-core/src/generic-solver.cc
In file included from /home/arocchi/Code/robotology-superbuild/external/roboptim-core/include/roboptim/core/differentiable-function.hh:261:0,
                 from /home/arocchi/Code/robotology-superbuild/external/roboptim-core/include/roboptim/core/util.hxx:28,
                 from /home/arocchi/Code/robotology-superbuild/external/roboptim-core/include/roboptim/core/util.hh:165,
                 from /home/arocchi/Code/robotology-superbuild/external/roboptim-core/include/roboptim/core/function.hxx:33,
                 from /home/arocchi/Code/robotology-superbuild/external/roboptim-core/include/roboptim/core/function.hh:603,
                 from /home/arocchi/Code/robotology-superbuild/external/roboptim-core/include/roboptim/core/problem.hh:31,
                 from /home/arocchi/Code/robotology-superbuild/external/roboptim-core/include/roboptim/core/generic-solver.hh:36,
                 from /home/arocchi/Code/robotology-superbuild/external/roboptim-core/src/generic-solver.cc:22:
/home/arocchi/Code/robotology-superbuild/external/roboptim-core/include/roboptim/core/differentiable-function.hxx: In member function ‘void roboptim::GenericDifferentiableFunction<T>::impl_jacobian(roboptim::GenericDifferentiableFunction<T>::jacobian_ref, roboptim::GenericDifferentiableFunction<T>::const_argument_ref) const [with T = roboptim::EigenMatrixSparse; roboptim::GenericDifferentiableFunction<T>::jacobian_ref = Eigen::SparseMatrix<double, 0>&; roboptim::GenericDifferentiableFunction<T>::const_argument_ref = const Eigen::Ref<const Eigen::Matrix<double, -1, 1> >&]’:
/home/arocchi/Code/robotology-superbuild/external/roboptim-core/include/roboptim/core/differentiable-function.hxx:52:46: error: conversion to ‘int’ from ‘Eigen::EigenBase<Eigen::SparseMatrix<double, 0> >::Index {aka long int}’ may alter its value [-Werror=conversion]
               (triplet_t (i, idx, it.value ()));
                                              ^
/home/arocchi/Code/robotology-superbuild/external/roboptim-core/include/roboptim/core/differentiable-function.hxx:52:46: error: conversion to ‘int’ from ‘Eigen::EigenBase<Eigen::SparseMatrix<double, 0> >::Index {aka long int}’ may alter its value [-Werror=conversion]
In file included from /home/arocchi/Code/robotology-superbuild/external/roboptim-core/include/roboptim/core/problem.hh:34:0,
                 from /home/arocchi/Code/robotology-superbuild/external/roboptim-core/include/roboptim/core/generic-solver.hh:36,
                 from /home/arocchi/Code/robotology-superbuild/external/roboptim-core/src/generic-solver.cc:22:
/home/arocchi/Code/robotology-superbuild/external/roboptim-core/include/roboptim/core/problem.hh: At global scope:
/home/arocchi/Code/robotology-superbuild/external/roboptim-core/build/include/roboptim/core/deprecated.hh:36:63: error: ‘roboptim::Problem<T>::scales_t’ is deprecated [-Werror=deprecated-declarations]
 #  define ROBOPTIM_CORE_DEPRECATED __attribute__ ((deprecated))
                                                               ^
/home/arocchi/Code/robotology-superbuild/external/roboptim-core/include/roboptim/core/problem.hh:211:33: note: in expansion of macro ‘ROBOPTIM_CORE_DEPRECATED’
     scales_t& argumentScales () ROBOPTIM_CORE_DEPRECATED;
                                 ^
/home/arocchi/Code/robotology-superbuild/external/roboptim-core/build/include/roboptim/core/deprecated.hh:36:63: note: declared here
 #  define ROBOPTIM_CORE_DEPRECATED __attribute__ ((deprecated))
                                                               ^
/home/arocchi/Code/robotology-superbuild/external/roboptim-core/include/roboptim/core/problem.hh:122:32: note: in expansion of macro ‘ROBOPTIM_CORE_DEPRECATED’
     typedef scaling_t scales_t ROBOPTIM_CORE_DEPRECATED;
                                ^
/home/arocchi/Code/robotology-superbuild/external/roboptim-core/build/include/roboptim/core/deprecated.hh:36:63: error: ‘roboptim::Problem<T>::scales_t’ is deprecated [-Werror=deprecated-declarations]
 #  define ROBOPTIM_CORE_DEPRECATED __attribute__ ((deprecated))
                                                               ^
/home/arocchi/Code/robotology-superbuild/external/roboptim-core/include/roboptim/core/problem.hh:214:45: note: in expansion of macro ‘ROBOPTIM_CORE_DEPRECATED’
     const scales_t& argumentScales () const ROBOPTIM_CORE_DEPRECATED;
                                             ^
/home/arocchi/Code/robotology-superbuild/external/roboptim-core/build/include/roboptim/core/deprecated.hh:36:63: note: declared here
 #  define ROBOPTIM_CORE_DEPRECATED __attribute__ ((deprecated))
                                                               ^
/home/arocchi/Code/robotology-superbuild/external/roboptim-core/include/roboptim/core/problem.hh:122:32: note: in expansion of macro ‘ROBOPTIM_CORE_DEPRECATED’
     typedef scaling_t scales_t ROBOPTIM_CORE_DEPRECATED;
                                ^
/home/arocchi/Code/robotology-superbuild/external/roboptim-core/build/include/roboptim/core/deprecated.hh:36:63: error: ‘roboptim::Problem<T>::scalesVect_t’ is deprecated [-Werror=deprecated-declarations]
 #  define ROBOPTIM_CORE_DEPRECATED __attribute__ ((deprecated))
                                                               ^
/home/arocchi/Code/robotology-superbuild/external/roboptim-core/include/roboptim/core/problem.hh:274:47: note: in expansion of macro ‘ROBOPTIM_CORE_DEPRECATED’
     const scalesVect_t& scalesVector () const ROBOPTIM_CORE_DEPRECATED;
                                               ^
/home/arocchi/Code/robotology-superbuild/external/roboptim-core/build/include/roboptim/core/deprecated.hh:36:63: note: declared here
 #  define ROBOPTIM_CORE_DEPRECATED __attribute__ ((deprecated))
                                                               ^
/home/arocchi/Code/robotology-superbuild/external/roboptim-core/include/roboptim/core/problem.hh:144:40: note: in expansion of macro ‘ROBOPTIM_CORE_DEPRECATED’
     typedef scalingVect_t scalesVect_t ROBOPTIM_CORE_DEPRECATED;
                                        ^
cc1plus: all warnings being treated as errors

```

When setting `USE_CXX11` these errors show up instead:

```
[  0%] Building CXX object src/CMakeFiles/roboptim-core.dir/generic-solver.cc.o
cd /home/arocchi/Code/robotology-superbuild/external/roboptim-core/build/src && /usr/bin/c++   -Droboptim_core_EXPORTS -I/home/arocchi/Code/robotology-superbuild/external/roboptim-core/build -I/home/arocchi/Code/robotology-superbuild/external/roboptim-core/build/include -I/home/arocchi/Code/robotology-superbuild/external/roboptim-core/include -isystem /usr/include/eigen3  -Werror  -pedantic -Wno-long-long -Wall -Wextra -Wcast-align -Wcast-qual -Wformat -Wwrite-strings -Wconversion -DROBOPTIM_DO_NOT_CHECK_ALLOCATION -fvisibility=hidden -DROBOPTIM_STORAGE_ORDER=ColMajor -fPIC   -I/usr/include/eigen3 -o CMakeFiles/roboptim-core.dir/generic-solver.cc.o -c /home/arocchi/Code/robotology-superbuild/external/roboptim-core/src/generic-solver.cc
In file included from /home/arocchi/Code/robotology-superbuild/external/roboptim-core/include/roboptim/core/differentiable-function.hh:261:0,
                 from /home/arocchi/Code/robotology-superbuild/external/roboptim-core/include/roboptim/core/util.hxx:28,
                 from /home/arocchi/Code/robotology-superbuild/external/roboptim-core/include/roboptim/core/util.hh:165,
                 from /home/arocchi/Code/robotology-superbuild/external/roboptim-core/include/roboptim/core/function.hxx:33,
                 from /home/arocchi/Code/robotology-superbuild/external/roboptim-core/include/roboptim/core/function.hh:603,
                 from /home/arocchi/Code/robotology-superbuild/external/roboptim-core/include/roboptim/core/problem.hh:31,
                 from /home/arocchi/Code/robotology-superbuild/external/roboptim-core/include/roboptim/core/generic-solver.hh:36,
                 from /home/arocchi/Code/robotology-superbuild/external/roboptim-core/src/generic-solver.cc:22:
/home/arocchi/Code/robotology-superbuild/external/roboptim-core/include/roboptim/core/differentiable-function.hxx: In member function ‘void roboptim::GenericDifferentiableFunction<T>::impl_jacobian(roboptim::GenericDifferentiableFunction<T>::jacobian_ref, roboptim::GenericDifferentiableFunction<T>::const_argument_ref) const [with T = roboptim::EigenMatrixSparse; roboptim::GenericDifferentiableFunction<T>::jacobian_ref = Eigen::SparseMatrix<double, 0>&; roboptim::GenericDifferentiableFunction<T>::const_argument_ref = const Eigen::Ref<const Eigen::Matrix<double, -1, 1> >&]’:
/home/arocchi/Code/robotology-superbuild/external/roboptim-core/include/roboptim/core/differentiable-function.hxx:52:46: error: conversion to ‘int’ from ‘Eigen::EigenBase<Eigen::SparseMatrix<double, 0> >::Index {aka long int}’ may alter its value [-Werror=conversion]
               (triplet_t (i, idx, it.value ()));
                                              ^
/home/arocchi/Code/robotology-superbuild/external/roboptim-core/include/roboptim/core/differentiable-function.hxx:52:46: error: conversion to ‘int’ from ‘Eigen::EigenBase<Eigen::SparseMatrix<double, 0> >::Index {aka long int}’ may alter its value [-Werror=conversion]
In file included from /home/arocchi/Code/robotology-superbuild/external/roboptim-core/include/roboptim/core/problem.hh:34:0,
                 from /home/arocchi/Code/robotology-superbuild/external/roboptim-core/include/roboptim/core/generic-solver.hh:36,
                 from /home/arocchi/Code/robotology-superbuild/external/roboptim-core/src/generic-solver.cc:22:
/home/arocchi/Code/robotology-superbuild/external/roboptim-core/include/roboptim/core/problem.hh: At global scope:
/home/arocchi/Code/robotology-superbuild/external/roboptim-core/build/include/roboptim/core/deprecated.hh:36:63: error: ‘roboptim::Problem<T>::scales_t’ is deprecated [-Werror=deprecated-declarations]
 #  define ROBOPTIM_CORE_DEPRECATED __attribute__ ((deprecated))
                                                               ^
/home/arocchi/Code/robotology-superbuild/external/roboptim-core/include/roboptim/core/problem.hh:211:33: note: in expansion of macro ‘ROBOPTIM_CORE_DEPRECATED’
     scales_t& argumentScales () ROBOPTIM_CORE_DEPRECATED;
                                 ^
/home/arocchi/Code/robotology-superbuild/external/roboptim-core/build/include/roboptim/core/deprecated.hh:36:63: note: declared here
 #  define ROBOPTIM_CORE_DEPRECATED __attribute__ ((deprecated))
                                                               ^
/home/arocchi/Code/robotology-superbuild/external/roboptim-core/include/roboptim/core/problem.hh:122:32: note: in expansion of macro ‘ROBOPTIM_CORE_DEPRECATED’
     typedef scaling_t scales_t ROBOPTIM_CORE_DEPRECATED;
                                ^
/home/arocchi/Code/robotology-superbuild/external/roboptim-core/build/include/roboptim/core/deprecated.hh:36:63: error: ‘roboptim::Problem<T>::scales_t’ is deprecated [-Werror=deprecated-declarations]
 #  define ROBOPTIM_CORE_DEPRECATED __attribute__ ((deprecated))
                                                               ^
/home/arocchi/Code/robotology-superbuild/external/roboptim-core/include/roboptim/core/problem.hh:214:45: note: in expansion of macro ‘ROBOPTIM_CORE_DEPRECATED’
     const scales_t& argumentScales () const ROBOPTIM_CORE_DEPRECATED;
                                             ^
/home/arocchi/Code/robotology-superbuild/external/roboptim-core/build/include/roboptim/core/deprecated.hh:36:63: note: declared here
 #  define ROBOPTIM_CORE_DEPRECATED __attribute__ ((deprecated))
                                                               ^
/home/arocchi/Code/robotology-superbuild/external/roboptim-core/include/roboptim/core/problem.hh:122:32: note: in expansion of macro ‘ROBOPTIM_CORE_DEPRECATED’
     typedef scaling_t scales_t ROBOPTIM_CORE_DEPRECATED;
                                ^
/home/arocchi/Code/robotology-superbuild/external/roboptim-core/build/include/roboptim/core/deprecated.hh:36:63: error: ‘roboptim::Problem<T>::scalesVect_t’ is deprecated [-Werror=deprecated-declarations]
 #  define ROBOPTIM_CORE_DEPRECATED __attribute__ ((deprecated))
                                                               ^
/home/arocchi/Code/robotology-superbuild/external/roboptim-core/include/roboptim/core/problem.hh:274:47: note: in expansion of macro ‘ROBOPTIM_CORE_DEPRECATED’
     const scalesVect_t& scalesVector () const ROBOPTIM_CORE_DEPRECATED;
                                               ^
/home/arocchi/Code/robotology-superbuild/external/roboptim-core/build/include/roboptim/core/deprecated.hh:36:63: note: declared here
 #  define ROBOPTIM_CORE_DEPRECATED __attribute__ ((deprecated))
                                                               ^
/home/arocchi/Code/robotology-superbuild/external/roboptim-core/include/roboptim/core/problem.hh:144:40: note: in expansion of macro ‘ROBOPTIM_CORE_DEPRECATED’
     typedef scalingVect_t scalesVect_t ROBOPTIM_CORE_DEPRECATED;
                                        ^
cc1plus: all warnings being treated as errors

```

**Comment by bchretien** [comment]
What is your version of gcc? And Eigen?

**Comment by arocchi** [comment]
`gcc --version`: 
```
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.2) 5.4.0 20160609
```
`pkg-config eigen3 --modversion`:
```
3.2.92
```

**Comment by bchretien** [comment]
I remember issues with GCC and wrong deprecated warnings, I will need to investigate this. As for the conversion warning, a cast may be missing. In the meantime, you can disable `-Werror` (`CXX_DISABLE_WERROR` needs to be defined).

**Comment by gergondet** [comment]
I'm going through the same process atm and I can confirm there is issues with compiling roboptim-core on xenial with Eigen 3.2.92, actually the build also breaks on trusty with Eigen 3.2.10 (I did not test with Eigen 3.2.9). There is two compilation issues that are errors.

The first problem is [there](https://github.com/roboptim/roboptim-core/blob/master/include/roboptim/core/problem.hxx#L425). There is a row operation on this line which is not supported for col-major sparse matrix (note: this has probably never worked with sparse matrix but since at least 3.2.10 this triggers a compilation error), this function is called in `tests/problem.cc` and the compilation fails there. (Note: the compilation error is more explicit if you rewrite the `*=` to `foo = foo * bar;`)

The second one is [there](https://github.com/roboptim/roboptim-core/blob/master/tests/util.cc#L268). The line above works fine. The error is only relevant to Eigen 3.2.90 (tested on 3.3.1 as-well)

The error I get (clang 3.8.0-2ubuntu4) is:
```
/home/gergondet/devel-src/pg/roboptim-core/include/roboptim/core/util.hxx:187:27: error: no type named 'InnerIterator' in 'Eigen::Block<Eigen::SparseMatrix<double, 0, int>, -1, -1,
      false>'
        typename block_t::InnerIterator b_it (b, k);
        ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
/home/gergondet/devel-src/pg/roboptim-core/tests/util.cc:268:25: note: in instantiation of function template specialization 'roboptim::updateSparseBlock<Eigen::SparseMatrix<double, 0,
      int>, Eigen::Block<Eigen::SparseMatrix<double, 0, int>, -1, -1, false> >' requested here
  BOOST_CHECK_NO_THROW (updateSparseBlock (sparse_c,
```

**Comment by bchretien** [comment]
Note: possible bug reported to the Eigen bugtracker by @gergondet  [here](http://eigen.tuxfamily.org/bz/show_bug.cgi?id=1359).

**Comment by gergondet** [comment]
The first issue was resolved in Eigen development branch (and so probably part of the next 3.3 release). I guess it won't be fixed in 3.2. Eigen devs have noted that:
```cpp
sm.middleRows(r, 1) *= n;
```
still compile fine in 3.2 (but not in 3.3 except on the current dev version).

We could:
1. Use `middleRows` and get (afaik) 3.2 and 3.3.2+ compatibility
2. Specialize `scaledJacobian` for sparse matrix and rewrite the `*=` line using `InnerIterator` and get 3.2.n (n<10) and 3.3 (including beta1) compatibility
3. A mix of both (`middleRows` in 3.2, specialized version in 3.3) to get both

For the second problem, based on the [fix](https://bitbucket.org/eigen/eigen/commits/b2fecf173f2a/) required for the first issue, I've come up with a solution, which is to replace:
```cpp
typename block_t::InnerIterator b_it (b, k);
```
with
```cpp
typedef typename Eigen::internal::evaluator<block_t>::InnerIterator EvalIterator;
Eigen::internal::evaluator<block_t> thisEval(b);
EvalIterator b_it(thisEval, k);
```
(note: of course `thisEval` would only be constructed once)

This works only for Eigen 3.3 so here we also require different code for Eigen 3.2 and 3.3.

Assuming we go with option 2 or 3, it should become possible to build roboptim-core in Ubuntu 16.04 with the default Eigen version.

If we go for a fix that includes distinct code for 3.2 and 3.3, should we introduce a new macro in `portability.hh` (e.g. `EIGEN_IS_3_3`)?

**Comment by bchretien** [comment]
@gergondet Thanks a lot for analyzing the issue :+1: 

For the first problem, we should aim at supporting both Eigen 3.2 and 3.3. We can also add a template inline method that implements the scaling of the row, and specialize it for sparse matrices. That way all versions are covered (as far as we know), and we avoid too much code duplication. Later on we can improve it for cache efficiency (row-major / column-major being both supported), but for now we should at least have the same efficiency. For that part, we would not need distinct code for Eigen 3.2 and 3.3 if I understood correctly.

For the second problem, if having a unique code working for both Eigen 3.2 and 3.3 is too difficult, I guess we can make a specific macro indeed.

**Comment by bchretien** [comment]
@arocchi: @gergondet took care of fixing the compilation for recent Eigen versions. Could you confirm that everything now works for you, so that I can close this issue?

**Comment by arocchi** [comment]
@bchretien @gergondet it compiles now, thanks!
